### ISSUE TITLE
[Nice-to-have] Shorthand for relative copy key references

### ISSUE THREAD

**Issue by nc-gibsonj** [NextCapital/copy-service#67]
## Problem

For easier readability and maintenance, it is good practice to break-up large sections of copy.
However, as a copy file grows and becomes more nested, key interpolation can become quite verbose.

Here's an example demonstrating this 'keep it manageable' pattern. Several paragraph copy keys are combined together by `pages.contributions.sections.copyService.description.primary`:
```
{
  "pages": {
    "contributions": {
      "sections": {
        "copyService": {
          "content": "${pages.contributions.sections.copyService.title}${pages.contributions.sections.copyService.description.primary}",
          "title": "<h3>Copy Service</h3>",
          "description": {
LONG -->    "primary": "${pages.contributions.sections.copyService.description.firstParagraph}${pages.contributions.sections.copyService.description.secondParagraph}${pages.contributions.sections.copyService.description.thirdParagraph}",
            "firstParagraph": "<p>Waves crash all around</p>",
            "secondParagraph": "<p>Comp calmly hums in the breeze</p>",
            "thirdParagraph": "<p>Sand in my keyboard</p>"
          }
        }
      }
    }
  }
}
```
But the `primary` value above is long and adds noticeably ugly clutter - in a way, violating the pattern the key was meant to implement.

## Solution Proposed

It would be easier to read something like this instead:
```
"primary": "${.firstParagraph}${.secondParagraph}${.thirdParagraph}"
```

So I propose a shorthand syntax, where a `.` prefixing the interpolated key causes a key lookup relative to the parent.
e.g., `"primary": "${.firstParagraph}"` above would tell the parser to lookup `firstParagraph` key relative to `primary`'s parent: `pages.contributions.sections.copyService.description`, resulting in the full key:
```
pages.contributions.sections.copyService.description.firstParagraph
```

**Comment by nc-gibsonj** [comment]
## Going Further

From conversations with @NC-piercej , the syntax could also allow key references relative to ancestors (beyond the immediate parent).
For example, a key `apples.buhnaynays.coconut.watermelon.cake => "...copyKey.path"`
 would attempt to lookup `apples.buhnaynays.copyKey.path`.

**Comment by NC-piercej** [comment]
To implement this, we'd need:

- A fourth argument to `evalAST`, namely the copy key currently being evaluated.
- A new `getAstForKey` method on the evaluator that:
  - Takes two arguments:
     - the key, potentially with relative syntax  
     - the root key to evaluate relative to
  - Calculates the key from the relative key (if necessary), and then defers to `copyService.getAstForKey`

**Comment by nc-gibsonj** [comment]
I figured it could be handled at a lower level, in CopyService, as to not disturb public interfaces and have to bump a major version. But if it's somehow better to implement this in Evaluator I can revise the current [PR](https://github.com/NextCapital/copy-service/pull/68)

**Comment by NC-piercej** [comment]
That works as well, I guess.
